### ISSUE TITLE
Create a Debit/Credit Button

### ISSUE THREAD

**Issue by ColleenMa** [EndianTribe/Reconcile-Issues-Tracker-Public#11]
Having to enter a “-“ sign to distinguish between debit and credit entries is not immediately obvious to all users. It is also very easy to forget. You should have a debit and a credit button at the bottom of the entry screen instead.

**Comment by EndianTribe** [comment]
This is a good suggestion. The app used to have Debit and Credit buttons but some other users reported confusion regarding their meaning. I plan to investigate the language apps like Venmo and Paypal use and implement an easier and less confusing way to log entries.

**Comment by EndianTribe** [comment]
Fixed in [de2c823fa2cce6f3b51ed31967fdd50ae41aef73](https://github.com/EndianTribe/expense-recon/commit/de2c823fa2cce6f3b51ed31967fdd50ae41aef73)
