### ISSUE TITLE
Allow for Account Name Change

### ISSUE THREAD

**Issue by ColleenMa** [EndianTribe/Reconcile-Issues-Tracker-Public#16]
Allow users to change/customize how their name displays in app when signing up. Some people might want to use a pseudo name for transactions.

**Comment by EndianTribe** [comment]
Unfortunately this is not possible with the vision of the app.

The app requires unique and verifiable authentication, which is accomplished through Google's federated single sign-on (using email as the unique ID). The display name is pulled directly from Google. In the same way Google (as well as many apps that deal with money such as Venmo and Splitwise) does not allow for aliases, Reconcile has chosen not to as well.
