### ISSUE TITLE
Value slider in search interface does not function

### ISSUE THREAD

**Issue by lidavidson** [EndianTribe/Reconcile-Issues-Tracker-Public#4]
It is not possible to move the "value" slider in the search functionality. The buttons at either end of the slider have a 'highlight' response in response to being tapped, but cannot be moved.

User is using a pixel 3 running Android 12

**Comment by EndianTribe** [comment]
Fixed in [04568859cd1bd86f9f97c7c45158dca357b49d46](https://github.com/EndianTribe/expense-recon/commit/04568859cd1bd86f9f97c7c45158dca357b49d46)
