### ISSUE TITLE
Unable to view 'notes' of ledger items

### ISSUE THREAD

**Issue by lidavidson** [EndianTribe/Reconcile-Issues-Tracker-Public#5]
There does not seem to be functionality to view any notes associated with a ledger item (apart from exporting the entire ledger). Tapping on individual ledger entries has no effect (not sure if this is intentional).

**Comment by EndianTribe** [comment]
I intend for the notes to show up once the user taps on the individual expense item (along with some other more detailed info about the expense). This is not yet implemented.
