### ISSUE TITLE
Unclear when a filter is applied

### ISSUE THREAD

**Issue by lidavidson** [EndianTribe/Reconcile-Issues-Tracker-Public#6]
[usability issue, rather than a bug]

When a filter is applied (e.g. only viewing transactions with a single person), there is no visible indicator in the UI that a filter has been applied and not all transactions are being shown.

**Comment by EndianTribe** [comment]
This is a good point I have not considered. I will need to show something on the main UI screen to indicate a search filter.

**Comment by EndianTribe** [comment]
Implemented in [96f5a8c4fe7db643216240c6be334e888135bd11](https://github.com/EndianTribe/expense-recon/commit/96f5a8c4fe7db643216240c6be334e888135bd11)
