### ISSUE TITLE
Can add infinite numbers after decimal

### ISSUE THREAD

**Issue by ColleenMa** [EndianTribe/Reconcile-Issues-Tracker-Public#8]
You can add infinite numbers after a decimal point in an entry. You should limit this to 2 digits.

**Comment by EndianTribe** [comment]
Fixed in [de2c823fa2cce6f3b51ed31967fdd50ae41aef73](https://github.com/EndianTribe/expense-recon/commit/de2c823fa2cce6f3b51ed31967fdd50ae41aef73)
