### ISSUE TITLE
Infinite Digits

### ISSUE THREAD

**Issue by ColleenMa** [EndianTribe/Reconcile-Issues-Tracker-Public#9]
You can make numbers infinitely large. Consider restricting size to actually reasonable limits. No one is completing a 10 quadtrillion dollar transaction.

**Comment by EndianTribe** [comment]
Fixed in [de2c823fa2cce6f3b51ed31967fdd50ae41aef73](https://github.com/EndianTribe/expense-recon/commit/de2c823fa2cce6f3b51ed31967fdd50ae41aef73)
